#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L " __  __                _              _  ____        _   ";
$L "|  \/  |              | |            | |/ __ \      | |  ";
$L "| \  / | __ _ _ __ ___| |__   ___  __| | |  | |_   _| |_ ";
$L "| |\/| |/ _` | '__/ __| '_ \ / _ \/ _` | |  | | | | | __|";
$L "| |  | | (_| | |  \__ \ | | |  __/ (_| | |__| | |_| | |_ ";
$L "|_|  |_|\__,_|_|  |___/_| |_|\___|\__,_|\____/ \__,_|\__|";
$L "Welcome to Android `getprop ro.build.version.release` / MarshedOut-`getprop ro.mo.version`";
